//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public int Id { get; set; }
        public int ProjectUserId { get; set; }
        public int ProjectId { get; set; }
        public int Type { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ProjectUser ProjectUser { get; set; }
        public virtual RoleName RoleName { get; set; }
    }
}
