//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatisticsData
    {
        public int Id { get; set; }
        public int ValueX { get; set; }
        public int ValueY { get; set; }
        public string NameX { get; set; }
        public string NameY { get; set; }
        public int StatisticsId { get; set; }
    
        public virtual Statistics Statistics { get; set; }
    }
}
