//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Assignment = new HashSet<Assignment>();
            this.Comment = new HashSet<Comment>();
            this.TaskStateChange = new HashSet<TaskStateChange>();
            this.Worktime = new HashSet<Worktime>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Priority { get; set; }
        public int EstimatedWorkHours { get; set; }
        public Nullable<int> MaxDevelopers { get; set; }
        public int ProjectId { get; set; }
        public int State { get; set; }
    
        public virtual ICollection<Assignment> Assignment { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual Project Project { get; set; }
        public virtual TaskState TaskState { get; set; }
        public virtual ICollection<TaskStateChange> TaskStateChange { get; set; }
        public virtual ICollection<Worktime> Worktime { get; set; }
    }
}
