//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskState
    {
        public TaskState()
        {
            this.Task = new HashSet<Task>();
            this.TaskStateChange = new HashSet<TaskStateChange>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Task> Task { get; set; }
        public virtual ICollection<TaskStateChange> TaskStateChange { get; set; }
    }
}
