CREATE TABLE [dbo].[Comment](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ProjectUserId] [int] NOT NULL,
	[TaskId] [int] NOT NULL,
	[Content] [nvarchar](4000) NOT NULL,
	[Timestamp] [datetime] NOT NULL,
 CONSTRAINT [PK_COMMENT] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Comment]  WITH CHECK ADD  CONSTRAINT [comment_fk1] FOREIGN KEY([TaskId])
REFERENCES [dbo].[Task] ([Id])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[Comment] CHECK CONSTRAINT [comment_fk1]
GO
ALTER TABLE [dbo].[Comment]  WITH CHECK ADD  CONSTRAINT [comment_fk2] FOREIGN KEY([ProjectUserId])
REFERENCES [dbo].[ProjectUser] ([Id])
GO

ALTER TABLE [dbo].[Comment] CHECK CONSTRAINT [comment_fk2]