CREATE TABLE [dbo].[Role](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ProjectUserId] [int] NOT NULL,
	[ProjectId] [int] NOT NULL,
	[Type] [int] NOT NULL,
 CONSTRAINT [PK_ROLE] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Role]  WITH CHECK ADD  CONSTRAINT [role_fk1] FOREIGN KEY([ProjectId])
REFERENCES [dbo].[Project] ([Id])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[Role] CHECK CONSTRAINT [role_fk1]
GO
ALTER TABLE [dbo].[Role]  WITH CHECK ADD  CONSTRAINT [role_fk2] FOREIGN KEY([ProjectUserId])
REFERENCES [dbo].[ProjectUser] ([Id])
GO

ALTER TABLE [dbo].[Role] CHECK CONSTRAINT [role_fk2]
GO
ALTER TABLE [dbo].[Role]  WITH CHECK ADD  CONSTRAINT [role_fk3] FOREIGN KEY([Type])
REFERENCES [dbo].[RoleName] ([Id])
GO

ALTER TABLE [dbo].[Role] CHECK CONSTRAINT [role_fk3]