CREATE TABLE [dbo].[Statistics]
(
	[Id] [int] IDENTITY(1,1) NOT NULL,
    [Name] NVARCHAR(50) NOT NULL, 
    [StartTime] DATETIME NULL, 
    [EndTime] DATETIME NULL,
	[ProjectId] INT NOT NULL, 
    [Public] BIT NOT NULL , 
    [LegendX] NVARCHAR(20) NULL, 
    [LegendY] NVARCHAR(20) NULL, 
    [CreatedDate] DATETIME NOT NULL, 
    CONSTRAINT [PK_STATISTICS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Statistics]  WITH CHECK ADD  CONSTRAINT [statistics_fk0] FOREIGN KEY([ProjectId])
REFERENCES [dbo].[Project] ([Id])
ON UPDATE CASCADE

GO
ALTER TABLE [dbo].[Statistics] CHECK CONSTRAINT [statistics_fk0]
