CREATE TABLE [dbo].[StatisticsData]
(
	[Id] [int] IDENTITY(1,1) NOT NULL,
    [ValueX] INT NOT NULL,
	[ValueY] INT NOT NULL,
	[NameX] NVARCHAR(20) NULL,
	[NameY] NVARCHAR(20) NULL,
    [StatisticsId] INT NOT NULL,
    CONSTRAINT [PK_STATISTICS_DATAX] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[StatisticsData]  WITH CHECK ADD  CONSTRAINT [statistics_data_fk0] FOREIGN KEY([StatisticsId])
REFERENCES [dbo].[Statistics] ([Id])
ON UPDATE CASCADE

GO
ALTER TABLE [dbo].[StatisticsData] CHECK CONSTRAINT [statistics_data_fk0]
